---
title: "Simulation Trials 2022-01-19"
output: html_document
---
```{r include=FALSE}
packages <- c('tidyverse', 'Cairo', 'dqrng')

installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}
invisible(lapply(packages, library, character.only = TRUE))
rm(packages, installed_packages)

simulateTrls <- function(trls, conf1, conf2, lo1, hi1, lo2, hi2) {
  RNG <<- tibble(
    trlNum = rep(1:trls),
    outCome = if_else(dqrunif(trls) < .5, 0, 1),
    confRNG1 = dqrunif(trls),
    confRNG2 = dqrunif(trls),
    accRNG1 = dqrunif(trls),
    accRNG2 = dqrunif(trls),
    confA1 = if_else(confRNG1 < conf1, 0, 1),
    accA1 = if_else(
      confA1 == 1,
      if_else(accRNG1 < hi1, 1, 0),
      if_else(accRNG1 < lo1, 1, 0)
    ),
    
    confA2 = if_else(confRNG2 < conf2, 0, 1),
    accA2 = if_else(
      confA2 == 1,
      if_else(accRNG2 < hi2, 1, 0),
      if_else(accRNG2 < lo2, 1, 0)
    )
  )
  
  varName = c('lo', 'hi')
  for (i in 0:1) {
    assign(
      paste0('A1', varName[i + 1]),
      filter(RNG, confA1 == i) %>%
        mutate(
          winSum = cumsum(accA1),
          test = 1:length(winSum),
          proportion = winSum / test,
          group = paste0('A1', varName[i + 1])
          
        ),
      envir = globalenv()
    )
    
    assign(
      paste0('A2', varName[i + 1]),
      filter(RNG, confA2 == i) %>%
        mutate(
          winSum = cumsum(accA2),
          test = 1:length(winSum),
          proportion = winSum / test,
          group = paste0('A2', varName[i + 1])
          
        ),
      envir = globalenv()
    )
  }
  
  graphData <<- bind_rows(A1hi,
                          A1lo,
                          A2hi,
                          A2lo) %>%
    arrange(group) %>%
    select(trlNum, proportion, group)
}


```

Generate RNG to determine high low confidence response (50/50)
for high/low confidence, probability of correct response is (80/60) for calibrated, or (70/70) for non-calibrated

1st one is set to (50/50) and (75/25) just for demonstration

```{r echo=FALSE, R.options = list(width = 130)}
simulateTrls(2000, .5, .5, .25, .75, .5, .5)
print(RNG)
print(A1hi)
print(A1lo)
print(A2hi)
print(A2lo)

ggplot(graphData,
       aes(
         x = trlNum,
         y = proportion,
         group = group,
         color = group
       )) +
  scale_color_manual(
    values = c(
      A1hi = 'red',
      A1lo = 'blue',
      A2hi = 'orange',
      A2lo = 'green'
    ),
    name = 'Advisor Judgement',
    labels=c('Calibrated High', 'Calibrated Low', 'Non-Calibrated High', 'Non-Calibrated Low')
  ) +
  labs(title = "Simulated Correct Proportions",
       y = "Proportion Correct", x = "Trial Number") +
  coord_cartesian(ylim = c(0,1)) +
  geom_line()


simulateTrls(2000, .5, .5, .8, .6, .7, .7)
ggplot(graphData,
       aes(
         x = trlNum,
         y = proportion,
         group = group,
         color = group
       )) +
  scale_color_manual(
    values = c(
      A1hi = 'red',
      A1lo = 'blue',
      A2hi = 'orange',
      A2lo = 'green'
    ),
    name = 'Advisor Judgement',
    labels=c('Calibrated High', 'Calibrated Low', 'Non-Calibrated High', 'Non-Calibrated Low')
  ) +
  labs(title = "Simulated Correct Proportions",
       y = "Proportion Correct", x = "Trial Number") +
  coord_cartesian(ylim = c(0,1)) +
  geom_line()

simulateTrls(2000, .5, .5, .8, .6, .7, .7)
ggplot(graphData,
       aes(
         x = trlNum,
         y = proportion,
         group = group,
         color = group
       )) +
  scale_color_manual(
    values = c(
      A1hi = 'red',
      A1lo = 'blue',
      A2hi = 'orange',
      A2lo = 'green'
    ),
    name = 'Advisor Judgement',
    labels=c('Calibrated High', 'Calibrated Low', 'Non-Calibrated High', 'Non-Calibrated Low')
  ) +
  labs(title = "Simulated Correct Proportions",
       y = "Proportion Correct", x = "Trial Number") +
  coord_cartesian(ylim = c(0,1)) +
  geom_line()

simulateTrls(2000, .5, .5, .8, .6, .7, .7)
ggplot(graphData,
       aes(
         x = trlNum,
         y = proportion,
         group = group,
         color = group
       )) +
  scale_color_manual(
    values = c(
      A1hi = 'red',
      A1lo = 'blue',
      A2hi = 'orange',
      A2lo = 'green'
    ),
    name = 'Advisor Judgement',
    labels=c('Calibrated High', 'Calibrated Low', 'Non-Calibrated High', 'Non-Calibrated Low')
  ) +
  labs(title = "Simulated Correct Proportions",
       y = "Proportion Correct", x = "Trial Number") +
  coord_cartesian(ylim = c(0,1)) +
  geom_line()

simulateTrls(2000, .5, .5, .8, .6, .7, .7)
ggplot(graphData,
       aes(
         x = trlNum,
         y = proportion,
         group = group,
         color = group
       )) +
  scale_color_manual(
    values = c(
      A1hi = 'red',
      A1lo = 'blue',
      A2hi = 'orange',
      A2lo = 'green'
    ),
    name = 'Advisor Judgement',
    labels=c('Calibrated High', 'Calibrated Low', 'Non-Calibrated High', 'Non-Calibrated Low')
  ) +
  labs(title = "Simulated Correct Proportions",
       y = "Proportion Correct", x = "Trial Number") +
  coord_cartesian(ylim = c(0,1)) +
  geom_line()

simulateTrls(2000, .5, .5, .8, .6, .7, .7)
ggplot(graphData,
       aes(
         x = trlNum,
         y = proportion,
         group = group,
         color = group
       )) +
  scale_color_manual(
    values = c(
      A1hi = 'red',
      A1lo = 'blue',
      A2hi = 'orange',
      A2lo = 'green'
    ),
    name = 'Advisor Judgement',
    labels=c('Calibrated High', 'Calibrated Low', 'Non-Calibrated High', 'Non-Calibrated Low')
  ) +
  labs(title = "Simulated Correct Proportions",
       y = "Proportion Correct", x = "Trial Number") +
  coord_cartesian(ylim = c(0,1)) +
  geom_line()

```
